# Generated by Django 5.1.3 on 2024-11-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='usuario',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='vinculado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='nome_setor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('A Fazer', 'A Fazer'), ('Fazendo', 'Fazendo'), ('Pronto', 'Pronto')], default='A Fazer', max_length=10),
        ),
    ]
